### ISSUE TITLE
Broken Test

### ISSUE THREAD

**Issue by nmortell** [metten0/moby_dick_word_frequency_exercise#3]
✕ should exist as a function (9ms)
  ✓ should throw an error if either parameters are not arrays (1ms)
  ✓ should return an empty array given an empty string and object (3ms)
  ✓ should remove Stop Words from the results (1ms)

**Comment by nmortell** [comment]
resulting output from npm test

**Comment by metten0** [comment]
Repaired by adding jest-extended. Thank you.

**Comment by metten0** [comment]
All tests now passing.
